name: Release

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm install --frozen-lockfile

            - name: Build Web App to /dist
              run: npm run export-web

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Tag and Create Release
              if: steps.changesets.outputs.hasChangesets == 'false'
              # You can do something when a publish should happen.
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  git tag "v$VERSION"
                  git push origin "v$VERSION"
                  curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -d '{"tag_name": "v'$VERSION'", "name": "Release v'$VERSION'", "body": "Release version v'$VERSION'", "draft": false, "prerelease": false}' \
                    https://api.github.com/repos/${{ github.repository }}/releases
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
