name: Release

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm install --frozen-lockfile

            - name: Build Web App to /dist
              run: npm run export-web

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Tag and Release via gh cli - If no changesets exist
              if: steps.changesets.outputs.hasChangesets == 'false'
              # at this point, theres no changesets, so create a release if it doesn't already exist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION=$(node -p "require('./package.json').version")                
                  gh release view "v$VERSION"

                  if gh release view "v$VERSION" > /dev/null 2>&1; then
                    echo "Release v$VERSION already exists."
                  else
                    echo "Release v$VERSION does not exist. Creating release..."
                    gh release create v$VERSION --title "v$VERSION" --notes "Automated release of v$VERSION"
                  fi
